services:
  imagenesservice:
    build:
      context: .
      dockerfile: ImagenesService/Dockerfile
    container_name: imagenesservice
    restart: always
    ports:
      - "5005:8080"
    volumes:
      - /DATA/imagenes:/app/wwwroot/images
    networks:
      - erpnetwork

  nginx:
    image: nginx:latest
    container_name: nginx
    restart: always
    ports:
      - "8080:8080"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    networks:
      - erpnetwork

networks:
  erpnetwork:
    driver: bridge
