version: '3.8'

services:

  imagenesservice:
    image: imagenesservice
    container_name: imagenesservice
    restart: always
    volumes:
      - /DATA/imagenes:/app/wwwroot/images
    networks:
      - erpnetwork

  nginx:
    image: nginx:latest
    container_name: nginx
    depends_on:
      - imagenesservice
    restart: always
    ports:
      - "5211:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
